### ISSUE TITLE
U I

### ISSUE THREAD

**Issue by PityBr** [alisonrag/vue-visual-simulator#1]
hi alisson, you don't know me but we have common interests, i know it's sudden but do you know anyone with the nick of Smike? Also, is it possible for your old Ragnarok bot to work on the BRO server?

**Comment by alisonrag** [comment]
Hi, i don't remember anyone that has nick of Smike. This repository is related to another project, and about bot, its not working.

**Comment by PityBr** [comment]
There is no way to bypass Easy Auto Cheat, at least you start?
