### ISSUE TITLE
C_White_Feather item

### ISSUE THREAD

**Issue by aleDsz** [alisonrag/vue-visual-simulator#2]
Hi Alison, The [C_White_Feather](https://divine-pride.net/database/item/20078/boina-de-penas) item have another sprite on jRO server, but bRO uses the old [C_Feather_Beret](https://divine-pride.net/database/item/19585/boina-alada-visual) sprite. Would you accept a PR to change that?

![image](https://user-images.githubusercontent.com/6402997/178145906-f9c1fe9c-6b8f-4baf-8a8c-5e8a626863b1.png)

**Comment by alisonrag** [comment]
yep, just do it ;]

**Comment by aleDsz** [comment]
Hmmm, I've check how the application gets the sprite, but it seem to be from the server-side, so it only would work if the server-side accepts the "headgear server type", which we would set if it should be based on X server to get the sprite
