### ISSUE TITLE
Shadow Chaser second costume

### ISSUE THREAD

**Issue by qrewx** [alisonrag/vue-visual-simulator#3]
Only Male Shadow Chaser can't change this second costume 
![Capture](https://user-images.githubusercontent.com/124495337/216814229-690b83b1-c7fe-40d2-bc37-335cbfe7ce64.JPG)

**Comment by alisonrag** [comment]
cant reproduce your issue:
![image](https://user-images.githubusercontent.com/10372732/216833539-0e645cca-a510-4b70-9219-c9cf17356953.png)


are you using my API or your own API?
