### ISSUE TITLE
my character doesn't show up

### ISSUE THREAD

**Issue by luksrio29** [alisonrag/vue-visual-simulator#4]
Hello,

I'm trying to use the site, but my character does not appear. I have tried on two browsers (Brave and Edge) and in both I have problem.
![Screenshot_4](https://user-images.githubusercontent.com/126081174/220631104-929ddfea-cc7d-471b-a3fb-bee33d9cd4a5.png)

**Comment by alisonrag** [comment]
just use http, instead of https, i dont have a SSL certificate at backend so only work at http
