### ISSUE TITLE
Erro na visualização de personagens

### ISSUE THREAD

**Issue by NovembroFenix** [alisonrag/vue-visual-simulator#5]
Olá! tudo bem? notei que vários membros da comunidade (https://chat.whatsapp.com/Lf3IBUraREHL2h5pDV58pS) estão com problemas para visualizar os personagens:
![image](https://user-images.githubusercontent.com/131807541/234365415-4b4400ee-8f77-44ed-ba70-b9cd87cb6bd8.png)

Poderia conseguir uma solução? Alías sou Designer Gráfico, se eu puder cooperar com seu Ragvisu, fique a vontade para me comunicar: andersonguimaraes1894@gmail.com

**Comment by alisonrag** [comment]
a api de renderização esta offline, estava usando o free tier do google, porém acabou o tempo, ja estou estudando passar pra outro lugar, mas ando ocupado com o serviço.

Ambos os projetos sao open source, se quiser contribuir sinta-se a vontade:
https://github.com/alisonrag/vue-visual-simulator/pulls
https://github.com/zhad3/zrenderer/pulls

**Comment by alisonrag** [comment]
esta de volta no ar: http://www.visualrag.com/
