### ISSUE TITLE
Hairs 11 and 12 are swapped

### ISSUE THREAD

**Issue by euclydesbsn** [alisonrag/vue-visual-simulator#7]
![image](https://user-images.githubusercontent.com/7103249/235224987-82106376-4f46-4049-87fe-7b861d2d3d91.png)
![image](https://user-images.githubusercontent.com/7103249/235225018-6f9713e2-4f0f-47f5-b9ce-893f4a485d31.png)

Shouldn't be something hard to fix but my Vue knowledge is none, so the best I can do is open this issue.
Your tool is great, man! Thanks for creating it!

**Comment by alisonrag** [comment]
fixed at: https://github.com/alisonrag/vue-visual-simulator/commit/186a26937d4e442914422709446e8e9a78f853bf

seems like bRO messed with the hair order
