### ISSUE TITLE
Doram's summoner colors not changing

### ISSUE THREAD

**Issue by player700** [alisonrag/vue-visual-simulator#9]
![Screenshot 2023-07-31 at 00-39-06 Ragnarok Online Visual Simulator](https://github.com/alisonrag/vue-visual-simulator/assets/140996686/7cc974ec-214e-46f4-85bc-fdc421bce607)
![Screenshot 2023-07-31 at 00-39-15 Ragnarok Online Visual Simulator](https://github.com/alisonrag/vue-visual-simulator/assets/140996686/a775356e-424c-4522-a9f3-dbd3d15dd63b)
Doesn't work for both male and females characters, you probably forgot to implement them or something

**Comment by alisonrag** [comment]
Fixed, thanks for report: 
![47114540-171b-4384-b33a-7d5801c259e6](https://github.com/alisonrag/vue-visual-simulator/assets/10372732/5f41a3be-cb6b-4a73-939c-cf30f63ba394) ![6ee01e53-b928-4f4f-ba63-1baeb8847357](https://github.com/alisonrag/vue-visual-simulator/assets/10372732/1fa1ee10-7e48-41dc-82f8-115492dcadd0)
